# Build matrix
language: node_js
sudo: required

matrix:
  include:

    # Lint only in Node.js 6
    - node_js: '6'
      env: MODE=lint

    # Run tests in Node.js 6
    - node_js: '6'

    # Run tests in Node.js 8
    - node_js: '8'

    # Pa11y check only in Node.js 8
    - node_js: '8'
      env: MODE=pa11y

# Build script
script:
  - 'if [ ! $MODE ]; then npm test; fi'
  - 'if [ $MODE == "lint" ]; then npm run lint; fi'
  - 'if [ $MODE == "pa11y" ]; then npm run test-pa11y; fi'
